add skip/seek backwards button
amosproj/amos2022ws02-automotive-test-app pull request #181
Opened 2023-01-11 15:27 UTC by tobischmd

Signed-off-by: Tobias Schmid <tobias.schmid@fau.de>

2023-01-11 15:28 UTC, tobischmd commented
Gerne nochmal nachprüfen ob die KeyEvents auch wirklich auslösen, mein Emulator hat keinen MediaBrowser und deswegen hab ich das ganze mit der ARD Mediathek getestet, aber ich denke MEDIA_PREVIOUS und MEDIA_REWIND sollten die richtigen KeyEvents sein

2023-01-16 14:47 UTC, Andy3189 commented
STEP_BACKWARD und SKIP_BACKWARD haben auch merkbaren Effekt

2023-01-17 13:24 UTC, tobischmd commented
> STEP_BACKWARD und SKIP_BACKWARD haben auch keinen merkbaren Effekt

Hm mehr Media Events die irgendwie was mit zurückgehen/spulen sonst was symbolisieren gibts halt auch nicht

2023-01-18 10:10 UTC, Andy3189 requested changes
Wenn die POs sagen ist okay, dann ist okay, prinzipiell wäre noch nice erst meinen Branch zu mergen, weil ich das leicht angepasst habe mit den Keyevents

2023-01-18 10:11 UTC, Andy3189 commented
also meinen feature branch in diesen branch rein

2023-01-18 10:13 UTC, tobischmd commented
Bin eh grad am reviewen dann schau ich mir mal deinen PR auch an wenn alles passt merge ich den in dev und rebase dann meinen Branch

2023-01-18 10:31 UTC, Andy3189 commented
kannst du dann auch gleich mit den änderungen mergen, da sollte sich ja nix wirklcih ändern :D

2023-01-18 11:35 UTC, merged